"""
Django settings for tzxfz project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+ztmadtbvj5i&v_#xep38ki*_9c%&h9wnmf&!qx8=6=xe3cs-e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# *号也可以。
# ALLOWED_HOSTS：这个是要写服务器的ip地址，而不是浏览器的ip地址
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.xfzauth',
    'apps.news',
    'apps.course',
    'apps.payinfo',
    'apps.cms',
    'apps.ueditor',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tzxfz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins':['django.templatetags.static']
            #这一行的作用就是在前端的html模板文件中不需要每次都{% load static %},只需要写成static就可以了
        },
    },
]

WSGI_APPLICATION = 'tzxfz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django',
        'USER': 'wangdw',
        'PASSWORD': '123456',
        'HOST': '106.14.163.146',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# AUTH_USER_MODEL：这个属性，是django内置的，他会主动的到这个文件中来
# 查找这个属性，如果找到了，那么就会使用这个属性指定的模型来作为User对象
# AUTH_USER_MODEL：这个属性是一个字符串，他的规则是"appname.Modelname"
# 如果我们设置了AUTH_USER_MODEL，那么项目的makemigrations以及migrate命令
# 必须要在设置完这些东西以后再执行
AUTH_USER_MODEL = 'xfzauth.User'

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,"static"),
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# 七牛云相关的配置
QINIU_ACCESS_KEY = 'Km99s26x9Q4AXtp0LtxUX9sw0dZ0Z6UTYqAmzxBW'
QINIU_SECRET_KEY = 'M7GtcaeuHIjnJsYyhXH-ZmNdUqgezuDqBB9LjU-s'
QINIU_BUCKET_NAME = 'resource'
QINIU_DOMAIN = 'http://pbj56corq.bkt.clouddn.com/'



# UEditor相关的配置
UEDITOR_UPLOAD_TO_SERVER = True
UEDITOR_UPLOAD_PATH = MEDIA_ROOT
UEDITOR_CONFIG_PATH = os.path.join(BASE_DIR,'static','ueditor','config.json')


UEDITOR_QINIU_ACCESS_KEY = QINIU_ACCESS_KEY
UEDITOR_QINIU_SECRET_KEY = QINIU_SECRET_KEY
UEDITOR_QINIU_BUCKET_NAME = QINIU_BUCKET_NAME
UEDITOR_QINIU_DOMAIN = QINIU_DOMAIN
UEDITOR_UPLOAD_TO_QINIU = True

#表示新闻首页默认显示多少篇新闻数量，同时包括点击“加载更多”时一次加载3篇新闻
ONE_PAGE_NEWS_COUNT= 3


# 百度云的配置
# 控制台->用户中心->用户ID
# BAIDU_CLOUD_USER_ID = '5b8849ddc6504318abcea39fe620948e'
BAIDU_CLOUD_USER_ID = '69e7e0e76cd549558e75889cf2742d7f'
# 点播VOD->全局设置->发布设置->安全设置->UserKey
# BAIDU_CLOUD_USER_KEY = 'c228d166497b400d'
BAIDU_CLOUD_USER_KEY = 'b4f4d8ee427a4716'

#当用户没登陆时会跳转到登陆页面
LOGIN_URL = '/account/login/'